### ISSUE TITLE
Sample of using preact-i8n in combo with express

### ISSUE THREAD

**Issue by GoldenEagle007** [synacor/preact-i18n#14]
Hi,
I am looking for direction of what is the best way to use preact-i18n in preact but the locale is filtered at express end first. So the scenario is 
User hits the url, express would check the language in the header, based on that it will load the translation file  (like shown in bullet 2 of getting started)  and feed it to IntlProvider encompassing the preact component.
The idea is not to load all the translation file at the client end but only the one user needs.

If there is a sample/tutorial you can point to that would be really helpful. 
Thanks

**Comment by billneff79** [comment]
To solve the use case of not loading all translation files, the typical pattern would be to create chunks in the final build for each language file, using something like webpacks' [bundle-loader](https://github.com/webpack-contrib/bundle-loader), and then load the appropriate chunk asynchronously at runtime (using something like [split points](https://gist.github.com/developit/9f547d32b96f879b259be399a5dc0f01)) depending on which locale the end-user needs to see.  All of that can be handled in the client without the need for express to sit in front of it and would ensure that only one locale file is downloaded, not all of them.

**Comment by billneff79** [comment]
With that said, this is a common case and we should probably add documentation to the readme to that effect

**Comment by GoldenEagle007** [comment]
Thanks @billneff79 you make it sound so easy :-) . So would I have chunks for each language + route combination. If I have 3 languages and 2 routes that would mean 6 chunks. Is that correct ?

I agree we need more documentation on this as it would help in easy internationalization of apps developed using preact.
I will try your above suggestion and see how far I go.
