### ISSUE TITLE
Having multiple plural expressions in one string

### ISSUE THREAD

**Issue by chinchang** [synacor/preact-i18n#28]
Let's say I have this string: `You have 2 oranges and 5 bananas`. What do I provide in the `plural` prop when I have multiple numeric expressions to pluralize? Examples show passing only 1 value to `plural` prop.

**Comment by pl12133** [comment]
@chinchang Good question, you can use the `<Text>` component with nested `<Text>` components as fields to accomplish this:

```json
+ dictionary.json
{
  "fruits": {
    "youHave": "You have {{oranges}} and {{bananas}}",
    "oranges": {
      "none": "no oranges",
      "singular": "{{count}} orange",
      "plural": "{{count}} oranges"
    },
    "bananas": {
      "none": "no bananas",
      "singular": "{{count}} banana",
      "plural": "{{count}} bananas"
    },
  }
};
```

```js
function HowManyFruits({ orangeCount, bananaCount }) {
  return (
    <Text
      id="fruits.youHave"
      fields={{
        oranges: <Text id="fruits.oranges" fields={{ count: orangeCount }} plural={orangeCount} />,
        bananas: <Text id="fruits.bananas" fields={{ count: bananaCount }} plural={bananaCount} />
      }}
    />
  );
}
```

You can play around with this example here: https://jsfiddle.net/kup94zmy/1/

I think that answers the question so I'll close this out, but let me know if this is still an issue.

**Comment by donkeyDau** [comment]
This is not working for me. I have:
```{
  editEntity: "Edit '{{entityType}}'",
  entities: {
    CONS: 'Load'
   }
}```

```<Text id="editEntity" fields={{
    entityType: <Text id="entities.CONS" />,
}}
/>```

But it results in: `Edit '[object Object]'`

**Comment by pl12133** [comment]
@donkeyDau Please make sure you are using at least version `1.4.0` for this feature to work.

**Comment by donkeyDau** [comment]
Alright. I'm looking forward to this merge :)
