### ISSUE TITLE
Text is not rendered out when used as a field for Text

### ISSUE THREAD

**Issue by mogsdad** [synacor/preact-i18n#29]
Given a dictionary containing:
```
	"error": {
		"any": "Error: {{e}}",
		"genericInvalidRequest": "An unknown error has occurred."
	}
```

Providing `<Text>` as a field, like this: 
`<Text id="error.any" fields={{ e: <Text id="error.genericInvalidRequest" /> }} />`

Does not render the field:
`Error: [object Object]`

**Comment by pl12133** [comment]
Fixed by https://github.com/synacor/preact-i18n/pull/30
