### ISSUE TITLE
Add a hook version of withText for those who want to use hooks with Preact X?

### ISSUE THREAD

**Issue by craigdanj** [synacor/preact-i18n#41]
I was thinking we could use a hook version of the withText HOC. So developers who wish to use hooks can do something like:

`const firstName = useText('profile.user.firstName')`

**Comment by pl12133** [comment]
Fixed by https://github.com/synacor/preact-i18n/commit/a451350292148d1332a0321eb5bac34c076c2630 and released in `2.1.1-preactx`.

**Comment by Michael-1** [comment]
It would be good to have this officially documented.
