### ISSUE TITLE
IntlProvider doesn't even render children components.

### ISSUE THREAD

**Issue by skoshx** [synacor/preact-i18n#55]
This has been frustrating trying everything to get this to work, since l18n is something I need. I have a basic app just to get everything working, but it doesn't even work, even if its the same as in the examples in the documentation... Snippet:

```javascript
render() {
    console.log("This prints");
    const AppB = () => {
      console.log("This doesn't even print for some reason");
      return (
        <div id="app">
          <div>content</div>
        </div>
      );
    }
    return (
      <IntlProvider definition={defaultDefinition}>
        <AppB />
      </IntlProvider>
    );
  }
```

AppB functional component is not rendered, ITS NOT EVEN BEING CALLED, somehow?!

**Comment by pl12133** [comment]
You may need to check that your version of `preact` is in sync with your `preact-i18n` version. If you have `preact>=10` you will want to use the `preact-i18n@preactx` version with `npm install preact-i18n@preactx`.

I think it may have been a long enough time that we can cut over the `preactx` tag to the latest version so people don't run into this too often.
