### ISSUE TITLE
Consider re-licensing to MIT or AL v2.0

### ISSUE THREAD

**Issue by bjankord** [synacor/preact-i18n#8]
Hi there,

With all the licensing issues going on with React / the ASF foundation, I'm curious if you all would be interested in re-licensing preact-i18n to a MIT License, similar to how preact is currently licensed or re-license to Apache License 2.0.

Thanks for your consideration.

**Comment by pl12133** [comment]
Is there an issue preventing you from using this library under the [BSD 3-clause](https://github.com/synacor/preact-i18n/blob/master/LICENSE) license? This license [is permitted to be included with Apache products](https://www.apache.org/legal/resolved.html#category-a).

This is not a [Category X License](https://www.apache.org/legal/resolved.html#category-x) like the recently re-categorized [Facebook BSD+Patents License](https://code.facebook.com/pages/850928938376556); unless I am mistaken.

**Comment by bjankord** [comment]
That is good to hear. Our team is looking to transition from react to preact due to FB licensing issues. With that, we'd be transitioning from react-intl to preact-i18n. Mainly wanted to have a sense of confidence that if we do this transition to preact, we reduce concerns about licensing issues. Thanks for the quick response @pl12133

**Comment by Aneurysm9** [comment]
We chose the 3-Clause BSD license for JavaScript projects targeting user agents precisely because it has very few interoperability concerns.  @bjankord if this addresses your concern, can we close this issue?  Thanks.

**Comment by bjankord** [comment]
+1, sgtm.
